### ISSUE TITLE
[Group13] An item can have multiple locations

### ISSUE THREAD

**Issue by ishanfdo18098** [cepdnaclk/smart-inventory-management-system#166]
- [x] Separate page to add item locations
    - Each items index page has a button to add locations to the item
    - Clicking that button shows a new page that has all the locations listed, User can click to add item to that location
    -  [x] Implement for equipments and notify Mr. Nuwan Jaliyagoda
    -  [x] Equipment
   -  When approved, implement the same for
      - [x] Component
      - [x] Consumble
      - [x] Machines
      - [x] Raw material
- [x] Add mutlitple locations support to **_frontend_** item pages
  - [x]  Equipment
  - [x]  Component
  - [x] Consumable
- [x] Add mutlitple locations support to **_backend_** item pages
  - [x]  Equipment
  - [x]  Component
  - [x] Consumable
- [x] Add Locations Menus
  - [x] Controller
  - [x] Views
  - [x] Routes
- [x] Add Tests
  - [x] Backend edit locations livewire
  - [x] frontend equipment items locations
  - [x] frontend consumable items locations
  - [x] frontend component items locations
  - [x] backend equipment items locations
  - [x] backend consumable items locations
  - [x] backend component items locations
  - [x] LocationsControllerTest

**Comment by ishanfdo18098** [comment]
Add mutlitple locations support to frontend item pages - Consumable

![image](https://user-images.githubusercontent.com/73381996/177683211-6b9255a3-23ee-4f61-b7ca-347bd1479999.png)

**Comment by ishanfdo18098** [comment]
@NuwanJ Multiple locations can now be added to Equipments. Please check and confirm.

**Comment by NuwanJ** [comment]
I will made a PR into my copy, check it and let you know

**Comment by NuwanJ** [comment]
@ishanfdo18098 Where we can enter and add new Locations?

**Comment by ishanfdo18098** [comment]
> @ishanfdo18098 Where we can enter and add new Locations?

I will implement that and let you know

**Comment by ishanfdo18098** [comment]
@NuwanJ New Locations can be added now.

https://github.com/ishanfdo18098/smart-inventory-management-system/commit/bacd84eb1068670188970c46b38daff3e729032f

![image](https://user-images.githubusercontent.com/73381996/178115846-65b0ec73-4a3c-465e-92d6-ee7f3faa2cad.png)

**Comment by ishanfdo18098** [comment]
Merged 425349a4550608195813f239af474986860d1944
