### ISSUE TITLE
[Group13] Add xyz coordinates to each item location for AR

### ISSUE THREAD

**Issue by ishanfdo18098** [cepdnaclk/smart-inventory-management-system#170]
- [x] Add xyz coordinates to each item location record for AR
- [x] Update factory (not updated - xyz coords are nulled by default)
- [x] Update database schema file in google drive
- [ ] Add them into create equipment page
- [ ] Add them into edit equipment page
- [ ] Notfiy Mr. Nuwan 
- [ ] Do the same to component, equipment, machine etc...

**Comment by NuwanJ** [comment]
In addition to the x,y, and z coordinates, I realized that we need to include how many units/copies of the items there are in the specific location.
