### ISSUE TITLE
A script to sync the uploaded files 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/smart-inventory-management-system#88]
The public folder (where the images and files are uploaded while adding items) is not included in the GitHub history. but the content will be available as a Google Drive folder in [here](https://drive.google.com/drive/folders/1_abJLk1GZ_smoq5ecs-hXdsz-HlgZJYu?usp=sharing).

it is better to have a script to download the contents into the public folder. (Python may be better)

**Comment by ishanfdo18098** [comment]
Downloading a folder from google drive without authentication is a bit problematic.  

Can I create a zip of the storage folder and upload that to drive then use that instead ?

**Comment by NuwanJ** [comment]
We will use 2 different environments for `Production` and `Development`, so this will be not a big issue.

I will include an option to zip the images in `Dev`, so anyone can easily sync them into their local environments
