### ISSUE TITLE
Feature: Consumables List

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/smart-inventory-management-system#92]
The main objective of this is to keep the track of the consumable items (Ex: Resistors, Capacitors, LEDs) in the inventory management system. Compared to other categories, the most important difference in this is the no need to keep the quantity of items 100% accurate. (But need to have a rough number)

Here, we need to have two Models, _Consumable Types_ and _Consumable Items_ 

TODO:
- [x] Database Design
  - [x] Types
  - [x] Items
- [x] Route Design
  - [x]  Consumable Types
  - [x] Consumable Items
- [x] Design the Views (Backend)
  - [x] Consumable Types
  - [x] Consumable Items
- [x] Design the Controllers and Models 
  - [x] Types
  - [x] Items
- [x] Design the Views (Frontend)
  - [x] Consumable Types
  - [x] Consumable Items
- [x] Seeders and Factories
  - [x] Consumable Types
  - [x] Consumable Items
- [x] Prepare Unit Tests
  - [x] Consumable Types
  - [x] Consumable Items

**Comment by ishanfdo18098** [comment]
Current consumable items in the lab - https://docs.google.com/spreadsheets/d/1cm-spnY7lHW8zHx7Cs14NR0U6IgCoovHSCEnYwKVjcM/edit#gid=954754003
